AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda layer for dynamodb client

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  StackEnvironment:
    Type: String
    Default: local
    AllowedValues:
      - prod
      - dev
      - local
Mappings:
  VarPerStack:
    prod:
      'Name': 'dynamodb-client'
    dev:
      'Name': 'dynamodb-client-dev'
    local:
      'Name': 'dynamodb-client-local'

Resources:
  DynamoDbClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !FindInMap [VarPerStack, !Ref 'StackEnvironment', Name]
      Description: lambda layer contains dynamodb client package
      CompatibleArchitectures:
        - arm64
        - x86_64
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs12.x
      ContentUri: ./layer
      RetentionPolicy: Retain
      LicenseInfo: MIT
